### ISSUE TITLE
[EG:gateway] rewrite plugin hasn't provided a schema. Validation for this plugin will be skipped.

### ISSUE THREAD

**Issue by danjesus** [ExpressGateway/express-gateway-plugin-rewrite#10]
After following the default install of the rewrite plugin it presents this message, and the rewrite does not work.

[EG:gateway] rewrite plugin hasn't provided a schema. Validation for this plugin will be skipped.

I am using version 1.7.2 of express gateway and version 1.1.1 of rewrite.

**Comment by XVincentX** [comment]
@danjesus 

Hey — thanks a lot for writing.

Can you provide some more details?
Is the gateway starting? Are you receiving any particular error message?

That warning is fine; the plugin itself is not providing any schema, but the exported policy and conditions are.

**Comment by danjesus** [comment]
Hi @XVincentX this is my gateway config

`http:
  port: 4005
admin:
  port: ${ADMIN_PORT:-9876}
  hostname: ${GATEWAY_HOSTNAME:-localhost}
apiEndpoints:
  sample_endpoint:
    host: ${GATEWAY_HOSTNAME:-localhost}
    paths:
      - /v1/*
serviceEndpoints:
  sample:
    urls:
      - ${SAMPLE_HOST}
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite
pipelines:
  default:
    apiEndpoints:
      - sample_endpoint
    policies:
      - rewrite:
        - condition:
            name: pathmatch
            match: /sample/*
          action:
            rewrite: /v1/*
      - proxy:
          - action:
              serviceEndpoint: sample
`

When I try to access the url of my localhost:4005/sample/test, it does not work, it only works by accessing localhost:4005/test directly, so rewrite does not work, apparently I'm doing everything, do you have any idea why it does not work?

**Comment by XVincentX** [comment]
You might want to use the `regexp` condition instead

```yml
            condition:
              name: regexpmatch
              match: ^/sample/(.*)$
            action:
              rewrite: /v1/$1
```

Just to clarify — for this particular use case you should use the `proxy` policy directly instead of the `rewrite`. It supports this use case.

**Comment by danjesus** [comment]
@XVincentX Thanks, have an example of how to use the proxy directly?

**Comment by krystianjj** [comment]
@XVincentX do you have example with using proxy directly ?
